name: Release (PR)

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-via-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Allow update-charts script to execute
        run: chmod +x ./update-charts.sh

      - name: Verify signatures
        run: npm audit signatures

      - name: Semantic Release
        id: semantic
        uses: codfish/semantic-release-action@v3
        with:
          branches: |
            ['develop']
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.semantic.outputs.release-version }}
      - run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}

      - name: Create a new branch, commit changes, push the branch, and create a PR
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          git checkout -b release/v${{ steps.semantic.outputs.release-version }}
          git add .
          git commit -m "chore(release): ${{ steps.semantic.outputs.release-version }}"
          git push origin release/v${{ steps.semantic.outputs.release-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR using GH CLI
        if: steps.semantic.outputs.new-release-published == 'true' && success()
        run: |
          gh pr create \
            --title "Release v${{ steps.semantic.outputs.release-version }}" \
            --body "${{ steps.semantic.outputs.release-notes }}" \
            --base develop \
            --head release/v${{ steps.semantic.outputs.release-version }}
            --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
