name: Sync

on:
  push:
    branches:
      - develop

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if PR exists
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --base main --head develop --repo ${{ github.repository }} | wc -l)
          echo "::set-output name=exists::$PR_EXISTS"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Pull Request
        if: steps.check_pr.outputs.exists == '0'
        run: |
          gh pr create \
            --title "Automated PR - Update main from develop" \
            --body "This is an automated pull request to update the main branch from the latest changes in develop." \
            --base main \
            --head develop \
            --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
